"""add due_at and completed_at to events

Revision ID: c45b2e8b1711
Revises: e0520140b700
Create Date: 2026-01-01 07:22:55.479071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45b2e8b1711'
down_revision: Union[str, Sequence[str], None] = 'e0520140b700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'completed_at')
    op.drop_column('events', 'due_at')
    # ### end Alembic commands ###
